# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token ba70dd5504eae50617362cb1d5039b0ebf54b28d

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###


POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 61f5b05861e018463f9e6005885d603c57dfaa88

{
  "title": "Стол Админский",
  "description": "Новый"
}

###


POST {{baseUrl}}/advertisements/
Content-Type: application/json

{
  "title": "--",
  "description": "=="
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/17/
Content-Type: application/json
Authorization: Token 61f5b05861e018463f9e6005885d603c57dfaa88

{
  "status": "OPEN"
}
###
# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/14/
Content-Type: application/json
Authorization: Token ba70dd5504eae50617362cb1d5039b0ebf54b28d

{
  "status": "CLOSED"
}
###

# попытка удалить объявление
DELETE  {{baseUrl}}/advertisements/11/
Content-Type: application/json
Authorization: Token 61f5b05861e018463f9e6005885d603c57dfaa88
###

# попытка удалить объявление
DELETE  {{baseUrl}}/advertisements/17/
Content-Type: application/json
Authorization: Token ba70dd5504eae50617362cb1d5039b0ebf54b28d
###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json
