# Generated by Django 5.2.11 on 2026-03-02 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_scope_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['-is_main', 'tag__name'], 'verbose_name': 'Тема новости', 'verbose_name_plural': 'Темы новостей'},
        ),
    ]
